#!/bin/bash
#*******************************************************************************
# Author            : Gin
# Gitlab            : https://github.com/indisukka
# Use               : Script to choose monitor layout
# Reference         : DT dmenu scripts, Luke Smith dmenu scripts video
#*******************************************************************************

declare -a options=(
"monitor"
"dual"
"manual"
    )

# Pipeing above array to dmenu
# using printf to format one item in a line
choice=$(printf '%s\n' "${options[@]}" | rofi -dmenu -i -p "Chose display output option")

case "$choice" in 
    monitor ) xrandr --output eDP-1 --off --output DP-1 --off --output DP-2 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP-3 --off --output DP-4 --off;;
    dual ) xrandr --output eDP-1 --mode 2880x1800 --pos 1920x0 --rotate normal --output DP-1 --off --output DP-2 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP-3 --off --output DP-4 --off;;
    manual ) arandr;;
esac 

feh --no-fehbg --bg-fill --randomize ~/Pictures/walls/* 