general.import = [
    "~/.config/alacritty/tomorrow-night.toml"
]

general.live_config_reload = true

[window]
dynamic_title = true
opacity = 0.98
startup_mode = "Maximized"

[scrolling]
history = 5000

[font]
size = 13

[font.normal]
family = "Office Code Pro"
style = "Regular"

[font.italic]
family = "Office Code Pro"
style = "Medium Italic"

[font.bold]
family = "Office Code Pro"
style = "Bold"

[font.bold_italic]
family = "Office Code Pro"
style = "Bold Italic"

[font.offset]
x = 0
y = 7

[cursor]
blink_interval = 750
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Underline"